# Generated by Django 5.2 on 2025-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
