# Generated by Django 5.2 on 2025-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_categorization_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='sentiment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
